### ISSUE TITLE
请问项目需要什么环境依赖？

### ISSUE THREAD

**Issue by guowei-gong** [hsuyeung/simple-blog#3]

**Comment by hsuyeung** [comment]
目前我服务器上运行环境的话就是 jdk1.8.0_341+mysql5.7.39+redis7.0.6，项目运行必要的依赖就这三个（版本仅供参考，可以根据自己需要升级）。
服务器上用的 nginx1.22.1 来作为反向代理和 https 配置

**Comment by hsuyeung** [comment]
本地开发环境的话，还需要安装 meven 进行依赖管理。

**Comment by guowei-gong** [comment]
tks u ans : )
